services:
  api:
    build: ./api
    environment:
      - MONGO_URI=${MONGO_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./quiz_app
      args:
        - VITE_API_URL=http://localhost:4000
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped