# File: .github/workflows/api-deploy.yml
name: CI/CD API via Azure CLI

on:
  push:
    # Only trigger when files in the api/ folder change
    paths:
      - 'api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build, login & push Docker image
        run: |
          IMAGE=chetannaruto07/quiz-app-api:latest

          # 1) Log in to Docker Hub in the same shell
          echo "${{ secrets.DOCKERHUB_TOKEN }}" \
            | docker login docker.io \
              --username "${{ secrets.DOCKERHUB_USERNAME }}" \
              --password-stdin

          # 2) Build for amd64
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag $IMAGE \
            ./api
      - name: Azure Login via Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Sync container on Azure Web App
        run: |
          az webapp deployment container sync \
            --resource-group quiz-api-rg \
            --name quiz-api