# File: .github/workflows/api-deploy.yml
name: CI/CD API via Azure CLI

on:
  push:
    # Only trigger when files in the api/ folder change
    paths:
      - 'api/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./api
          platforms: linux/amd64
          push: true
          tags: chetannaruto07/quiz-app-api:latest

      - name: Azure Login via Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Sync container on Azure Web App
        run: |
          az webapp deployment container sync \
            --resource-group quiz-api-rg \
            --name quiz-api